language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

script:
  - go get -d -t ./...
  - go vet ./...
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - >
    go_version=$(go version);
    if [ ${go_version:13:4} = "1.12" ]; then
      go get -u golang.org/x/tools/cmd/goimports;
      goimports -d -e ./ | grep '.*' && { echo; echo "Aborting due to non-empty goimports output."; exit 1; } || :;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
